id: A4E349CD0
title: The two premisses for Pravāraṇā
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:14:39.665728
  last_modified_at: 2022-03-01 22:14:39.665730
