id: A4E349CD0
title: Pravāraṇā only in the complete and pure congreagtion
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:14:39.658784
  last_modified_at: 2022-03-01 22:14:39.658791
