id: A4E349CD0
title: Four possible states of the matters when disagreement
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:14:39.650697
  last_modified_at: 2022-03-01 22:14:39.650700
