id: A4E349CD0
title: UddÄna 5
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:14:39.672016
  last_modified_at: 2022-03-01 22:14:39.672018
