id: A4E349CD0
title: Three kinds of Pravāraṇā according to the number of the participants
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:14:39.667894
  last_modified_at: 2022-03-01 22:14:39.667896
