id: A4E349CD0
title: UddÄna 7
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:14:39.675346
  last_modified_at: 2022-03-01 22:14:39.675349
