id: A4E349CD0
title: Pravāraṇā of a sick monk
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:14:39.655774
  last_modified_at: 2022-03-01 22:14:39.655777
