id: A4E349CD0
title: Not performing the Pravāraṇā befor all the recident monks are assembled
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:14:39.652414
  last_modified_at: 2022-03-01 22:14:39.652417
