id: A4E349CD0
title: Conditions for the just accusation (codanā) of a Bhikṣu and making the reality
  of the case clear
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:14:39.643803
  last_modified_at: 2022-03-01 22:14:39.643810
