id: A4E349CD0
title: Uddāna 2. Background for the establishemnet of the Pravāraṇākarma
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:14:39.669480
  last_modified_at: 2022-03-01 22:14:39.669483
