id: A4E349CD0
title: The cancelling of the Pravāraṇā because of, and against, a sick monk
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:14:39.664232
  last_modified_at: 2022-03-01 22:14:39.664235
