id: A4E349CD0
title: Canceling the Pravāraṇā because of absence
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:14:39.636876
  last_modified_at: 2022-03-01 22:14:39.636878
