id: A4E349CD0
title: Various forms of the ceremony in accordance with the numbers of repetition
  in the recitation of the Pravāraṇā fromula
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:14:39.676656
  last_modified_at: 2022-03-01 22:14:39.676658
